package httpapi
import("context";"encoding/csv";"encoding/json";"io";"net/http";"strconv";"strings";"time";"sync";"os";"github.com/google/uuid";"github.com/samanramezani1377-hub/crawler-numpo/internal/config";"github.com/samanramezani1377-hub/crawler-numpo/internal/capability";"github.com/samanramezani1377-hub/crawler-numpo/internal/discovery";"github.com/samanramezani1377-hub/crawler-numpo/internal/store";"github.com/samanramezani1377-hub/crawler-numpo/internal/crawl";"github.com/samanramezani1377-hub/crawler-numpo/internal/worker";"github.com/samanramezani1377-hub/crawler-numpo/internal/probe";"github.com/samanramezani1377-hub/crawler-numpo/internal/browser")
type Server struct{Store *store.Store;Cfg config.Config;Discovery *discovery.Service;Worker *worker.Worker;mu sync.Mutex;cancelFuncs map[string]context.CancelFunc}
func New(st *store.Store,cfg config.Config)*Server{return &Server{Store:st,Cfg:cfg,Discovery:&discovery.Service{Store:st},Worker:&worker.Worker{Store:st,Crawler:crawl.New(time.Duration(cfg.HTTPTimeoutSeconds)*time.Second,cfg.MaxBodyBytes),Prober:probe.New(time.Duration(cfg.HTTPTimeoutSeconds)*time.Second),Browser:func() browser.Renderer { if cfg.BrowserBinary!="" { return browser.NewChromiumRenderer(cfg.BrowserBinary,time.Duration(cfg.BrowserTimeoutSeconds)*time.Second,cfg.BrowserMaxOutput) }; return browser.DisabledRenderer{} }(),MaxPages:cfg.MaxPages,MaxCandidatesPerPage:cfg.MaxCandidatesPerPage,MaxDepth:cfg.MaxDepth,MaxURLs:cfg.MaxURLs,Lease:60*time.Second,DomainRateLimit:time.Duration(cfg.DomainRateLimitMS)*time.Millisecond,ProbeTTL:time.Duration(cfg.ProbeTTLSeconds)*time.Second,AllowSubdomains:cfg.AllowSubdomains,AllowExternalLinks:cfg.AllowExternalLinks},cancelFuncs:map[string]context.CancelFunc{}}}
func(s *Server)ServeHTTP(w http.ResponseWriter,r *http.Request){if r.URL.Path=="/api/v1/health"{s.health(w,r);return};if r.URL.Path=="/api/v1/metrics"{s.metrics(w,r);return};if !s.Cfg.AllowAnonymousAPI && (s.Cfg.APIKey=="" || r.Header.Get("Authorization")!="Bearer "+s.Cfg.APIKey){writeErr(w,401,"unauthorized","Authentication required.",false);return};switch{case r.Method==http.MethodPost&&r.URL.Path=="/api/v1/discovery/jobs":s.createJob(w,r);case r.Method==http.MethodPost&&strings.HasSuffix(r.URL.Path,"/cancel"):s.cancel(w,r);case r.Method==http.MethodGet&&strings.HasSuffix(r.URL.Path,"/candidates.csv"):s.exportCSV(w,r);case r.Method==http.MethodPost&&strings.HasSuffix(r.URL.Path,"/csv"):s.importCSV(w,r);case r.Method==http.MethodGet&&strings.HasSuffix(r.URL.Path,"/errors"):s.errors(w,r);case r.Method==http.MethodGet&&strings.HasPrefix(r.URL.Path,"/api/v1/discovery/jobs/"):s.job(w,r);default:writeErr(w,404,"not_found","Route not found.",false)}}
func(s *Server)createJob(w http.ResponseWriter,r *http.Request){defer r.Body.Close();var p struct{ProjectID string `json:"project_id"`;Mode string `json:"mode"`;Seeds []string `json:"seeds"`;Sources map[string]bool `json:"sources"`;Target map[string]any `json:"target"`;Limits map[string]int `json:"limits"`;Capabilities map[string]bool `json:"capabilities"`;RoutingRules []map[string]any `json:"routing_rules"`};if e:=json.NewDecoder(http.MaxBytesReader(w,r.Body,s.Cfg.MaxBodyBytes)).Decode(&p);e!=nil{writeErr(w,400,"invalid_json","Invalid JSON.",false);return};if p.ProjectID==""{writeErr(w,400,"invalid_project_id","project_id is required.",false);return};if p.Mode!="manual"&&p.Mode!="automatic"&&p.Mode!="hybrid"{writeErr(w,400,"invalid_discovery_mode","Discovery mode is invalid.",false);return};if p.Mode=="manual"&&len(p.Seeds)==0{writeErr(w,400,"manual_seeds_required","Manual mode requires seeds.",false);return};automatic:=p.Sources["search_provider"]||p.Sources["sitemap"]||p.Sources["robots"]||p.Sources["link_discovery"]||p.Sources["subdomain_from_crawl"];if p.Mode=="automatic"&&!automatic{writeErr(w,400,"automatic_source_required","Automatic mode requires at least one automatic source.",false);return};if p.Mode!="manual"&&len(p.Sources)==0{writeErr(w,400,"automatic_source_required","At least one discovery source is required.",false);return};cfg:=map[string]any{};caps:=capability.Defaults().Map();for k:=range caps{if v,ok:=p.Sources[k];ok{caps[k]=v}};for k,v:=range p.Capabilities{caps[k]=v};cfg["capabilities"]=caps;for k,v:=range p.Limits{if v<=0{continue};cfg[k]=v};cfg["sources"]=p.Sources;cfg["target"]=p.Target;if len(p.RoutingRules)>0{cfg["routing_rules"]=p.RoutingRules};for k,v:=range map[string]int{"max_pages":s.Cfg.MaxPages,"max_urls":s.Cfg.MaxURLs,"max_depth":s.Cfg.MaxDepth,"max_candidates_per_page":s.Cfg.MaxCandidatesPerPage}{if _,ok:=cfg[k];!ok{cfg[k]=v}};if cfg["max_pages"].(int)>s.Cfg.MaxPages{cfg["max_pages"]=s.Cfg.MaxPages};if cfg["max_urls"].(int)>s.Cfg.MaxURLs{cfg["max_urls"]=s.Cfg.MaxURLs};if cfg["max_depth"].(int)>s.Cfg.MaxDepth{cfg["max_depth"]=s.Cfg.MaxDepth};if cfg["max_candidates_per_page"].(int)>s.Cfg.MaxCandidatesPerPage{cfg["max_candidates_per_page"]=s.Cfg.MaxCandidatesPerPage};id:=uuid.NewString();if e:=s.Store.CreateDiscoveryJobWithConfig(r.Context(),id,p.ProjectID,p.Mode,cfg);e!=nil{writeErr(w,500,"internal_error","Could not create job.",true);return};if len(p.Seeds)>0{if e:=s.Discovery.Seed(r.Context(),id,p.Seeds);e!=nil{_ = s.Store.SetJobStatus(r.Context(),id,"failed");writeErr(w,400,"invalid_seed",e.Error(),false);return}};ctx,cancel:=context.WithCancel(context.Background());s.mu.Lock();s.cancelFuncs[id]=cancel;s.mu.Unlock();go s.runDiscovery(ctx,id,p.Mode,p.Sources,p.Target);write(w,202,map[string]any{"job_id":id,"status":"queued","mode":p.Mode,"created_at":time.Now().UTC()})}
func(s *Server)runDiscovery(ctx context.Context,job,mode string,sources map[string]bool,target map[string]any){defer func(){s.mu.Lock();delete(s.cancelFuncs,job);s.mu.Unlock()}();_=s.Store.SetJobStatus(ctx,job,"running");if mode!="manual"&&sources["search_provider"]&&s.Cfg.SearchURLTemplate!=""{query:="website";if v,ok:=target["technologies"].([]any);ok&&len(v)>0{var a []string;for _,x:=range v{if q,ok:=x.(string);ok{a=append(a,q)}};if len(a)>0{query=strings.Join(a," ")}};sp:=discovery.NewSearchProvider(time.Duration(s.Cfg.HTTPTimeoutSeconds)*time.Second,s.Cfg.SearchURLTemplate);if urls,e:=sp.Discover(ctx,query);e==nil{_ = s.Discovery.AddURLs(ctx,job,sp.Name(),urls,90)}};cands,e:=s.Store.Candidates(ctx,job);if e==nil{for _,c:=range cands{base,_:=c["url"].(string);if sources["sitemap"]{p:=discovery.NewSitemapProvider(discovery.NewHTTPProvider(time.Duration(s.Cfg.HTTPTimeoutSeconds)*time.Second));if urls,e:=p.Discover(ctx,base);e==nil{_ = s.Discovery.AddURLs(ctx,job,p.Name(),urls,70)}};if sources["robots"]{p:=discovery.NewRobotsProvider(discovery.NewHTTPProvider(time.Duration(s.Cfg.HTTPTimeoutSeconds)*time.Second));if urls,e:=p.Discover(ctx,base);e==nil{_ = s.Discovery.AddURLs(ctx,job,p.Name(),urls,60)}}}};_=s.Worker.Run(ctx,job)}
func(s *Server)job(w http.ResponseWriter,r *http.Request){parts:=strings.Split(strings.Trim(r.URL.Path,"/"),"/");if len(parts)<5{writeErr(w,404,"not_found","Job not found.",false);return};id:=parts[4];if len(parts)==6&&parts[5]!="candidates"&&parts[5]!="errors"{resource:=parts[5];switch resource{case "domains","hosts","pages","technologies","contacts","business","social","classifications","probes":default:writeErr(w,404,"not_found","Resource not found.",false);return};page:=1;if v,e:=strconv.Atoi(r.URL.Query().Get("page"));e==nil&&v>0{page=v};per:=50;if v,e:=strconv.Atoi(r.URL.Query().Get("per_page"));e==nil&&v>0&&v<=200{per=v};items,total,e:=s.Store.ListJobResource(r.Context(),id,resource,per,(page-1)*per);if e!=nil{writeErr(w,500,"internal_error",e.Error(),true);return};write(w,200,map[string]any{"items":items,"page":page,"per_page":per,"total":total});return};if len(parts)==6&&parts[5]=="candidates"{page:=1;per:=50;if v,e:=strconv.Atoi(r.URL.Query().Get("page"));e==nil&&v>0{page=v};if v,e:=strconv.Atoi(r.URL.Query().Get("per_page"));e==nil&&v>0&&v<=200{per=v};c,total,e:=s.Store.CandidatesPage(r.Context(),id,per,(page-1)*per);if e!=nil{writeErr(w,500,"internal_error",e.Error(),true);return};write(w,200,map[string]any{"items":c,"page":page,"per_page":per,"total":total});return};j,e:=s.Store.GetDiscoveryJob(r.Context(),id);if e!=nil{writeErr(w,404,"not_found","Job not found.",false);return};write(w,200,j)}
func(s *Server)metrics(w http.ResponseWriter,r *http.Request){
 ctx:=r.Context()
 var jobs,cands,queued,processing,retryable,dead,domains,pages int
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM discovery_jobs").Scan(&jobs)
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM candidates").Scan(&cands)
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM candidates WHERE status IN ('new','queued')").Scan(&queued)
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM candidates WHERE status='processing'").Scan(&processing)
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM candidates WHERE status='failed_retryable'").Scan(&retryable)
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM candidate_dead_letters").Scan(&dead)
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM domains").Scan(&domains)
 _=s.Store.DB.QueryRow(ctx,"SELECT count(*) FROM pages").Scan(&pages)
 lines:=[]string{
  "# HELP numpo_jobs_total Total discovery jobs.",
  "# TYPE numpo_jobs_total gauge",
  "numpo_jobs_total "+itoa(jobs),
  "# HELP numpo_candidates_total Total candidates.",
  "# TYPE numpo_candidates_total gauge",
  "numpo_candidates_total "+itoa(cands),
  "# HELP numpo_candidates_queued Current queued candidates.",
  "# TYPE numpo_candidates_queued gauge",
  "numpo_candidates_queued "+itoa(queued),
  "# HELP numpo_candidates_processing Current processing candidates.",
  "# TYPE numpo_candidates_processing gauge",
  "numpo_candidates_processing "+itoa(processing),
  "# HELP numpo_candidates_retryable Current retryable candidates.",
  "# TYPE numpo_candidates_retryable gauge",
  "numpo_candidates_retryable "+itoa(retryable),
  "# HELP numpo_dead_letters_total Total dead-letter candidates.",
  "# TYPE numpo_dead_letters_total gauge",
  "numpo_dead_letters_total "+itoa(dead),
  "# HELP numpo_domains_total Total domains.",
  "# TYPE numpo_domains_total gauge",
  "numpo_domains_total "+itoa(domains),
  "# HELP numpo_pages_total Total crawled pages.",
  "# TYPE numpo_pages_total gauge",
  "numpo_pages_total "+itoa(pages),
 }
 w.Header().Set("Content-Type","text/plain; version=0.0.4")
 w.WriteHeader(http.StatusOK)
 _,_=w.Write([]byte(strings.Join(lines,"\n")+"\n"))
}
func itoa(v int)string{if v==0{return "0"};s:="";for v>0{s=string(rune('0'+v%10))+s;v/=10};return s}
func write(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_ = json.NewEncoder(w).Encode(v)}
func writeErr(w http.ResponseWriter,status int,code,message string,retry bool){write(w,status,map[string]any{"error":map[string]any{"code":code,"message":message,"retryable":retry}})}
func(s *Server)cancel(w http.ResponseWriter,r *http.Request){parts:=strings.Split(strings.Trim(r.URL.Path,"/"),"/");if len(parts)<6{writeErr(w,404,"not_found","Job not found.",false);return};id:=parts[4];s.mu.Lock();if cancel,ok:=s.cancelFuncs[id];ok{cancel();delete(s.cancelFuncs,id)};s.mu.Unlock();if e:=s.Store.SetJobStatus(r.Context(),id,"cancelled");e!=nil{writeErr(w,404,"not_found","Job not found.",false);return};write(w,200,map[string]any{"job_id":id,"status":"cancelled"})}
func(s *Server)importCSV(w http.ResponseWriter,r *http.Request){defer r.Body.Close();parts:=strings.Split(strings.Trim(r.URL.Path,"/"),"/");if len(parts)<6{writeErr(w,404,"not_found","Job not found.",false);return};id:=parts[4];if r.ContentLength>s.Cfg.MaxBodyBytes{writeErr(w,413,"csv_too_large","CSV is too large.",false);return};rr:=csv.NewReader(http.MaxBytesReader(w,r.Body,s.Cfg.MaxBodyBytes));count:=0;line:=0;for{line++;rec,e:=rr.Read();if e!=nil{if e==io.EOF{break};writeErr(w,400,"invalid_csv","Invalid CSV at line "+strconv.Itoa(line)+".",false);return};if len(rec)==0||strings.TrimSpace(rec[0])==""{continue};raw:=strings.TrimSpace(rec[0]);if line==1&&strings.EqualFold(raw,"url"){continue};if e:=s.Discovery.AddURLs(r.Context(),id,"csv_import",[]string{raw},80);e!=nil{writeErr(w,400,"invalid_csv",e.Error(),false);return};count++};write(w,202,map[string]any{"job_id":id,"imported":count})}
func(s *Server)exportCSV(w http.ResponseWriter,r *http.Request){parts:=strings.Split(strings.Trim(r.URL.Path,"/"),"/");if len(parts)<6{writeErr(w,404,"not_found","Job not found.",false);return};id:=parts[4];items,e:=s.Store.Candidates(r.Context(),id);if e!=nil{writeErr(w,500,"internal_error",e.Error(),true);return};w.Header().Set("Content-Type","text/csv");w.Header().Set("Content-Disposition",`attachment; filename="numpo-candidates.csv"`);cw:=csv.NewWriter(w);_ = cw.Write([]string{"url","normalized_domain","source_type","priority","confidence","status","attempt_count"});for _,v:=range items{_ = cw.Write([]string{fmtString(v["url"]),fmtString(v["normalized_domain"]),fmtString(v["source_type"]),fmtString(v["priority"]),fmtString(v["confidence"]),fmtString(v["status"]),fmtString(v["attempt_count"])})};cw.Flush()}
func(s *Server)errors(w http.ResponseWriter,r *http.Request){parts:=strings.Split(strings.Trim(r.URL.Path,"/"),"/");if len(parts)<6{writeErr(w,404,"not_found","Job not found.",false);return};id:=parts[4];page:=1;if v,e:=strconv.Atoi(r.URL.Query().Get("page"));e==nil&&v>0{page=v};per:=50;if v,e:=strconv.Atoi(r.URL.Query().Get("per_page"));e==nil&&v>0&&v<=200{per=v};items,e:=s.Store.JobErrors(r.Context(),id,per,(page-1)*per);if e!=nil{writeErr(w,500,"internal_error",e.Error(),true);return};write(w,200,map[string]any{"items":items,"page":page,"per_page":per})}
func fmtString(v any)string{switch x:=v.(type){case string:return x;case int:return strconv.Itoa(x);case float64:return strconv.FormatFloat(x,'f',4,64);default:return ""}}
\nfunc(s *Server)health(w http.ResponseWriter,r *http.Request){\n components:=map[string]string{"database":"ok","browser":"disabled"}\n status:=http.StatusOK\n if s.Store==nil||s.Store.DB==nil { components["database"]="unavailable"; status=http.StatusServiceUnavailable } else if e:=s.Store.DB.Ping(r.Context());e!=nil { components["database"]="unavailable"; status=http.StatusServiceUnavailable }\n if strings.TrimSpace(s.Cfg.BrowserBinary)!="" { if _,e:=os.Stat(s.Cfg.BrowserBinary);e!=nil { components["browser"]="unavailable"; status=http.StatusServiceUnavailable } else { components["browser"]="ok" } }\n state:="ok"; if status!=http.StatusOK { state="degraded" }\n write(w,status,map[string]any{"status":state,"service":"numpo-engine","components":components})\n}\n