package httpapi
import("context";"encoding/json";"net/http";"strings";"time";"github.com/google/uuid";"github.com/samanramezani1377-hub/crawler-numpo/internal/config";"github.com/samanramezani1377-hub/crawler-numpo/internal/discovery";"github.com/samanramezani1377-hub/crawler-numpo/internal/store";"github.com/samanramezani1377-hub/crawler-numpo/internal/crawl";"github.com/samanramezani1377-hub/crawler-numpo/internal/worker")
type Server struct{Store *store.Store;Cfg config.Config;Discovery *discovery.Service;Worker *worker.Worker}
func New(st *store.Store,cfg config.Config)*Server{return &Server{Store:st,Cfg:cfg,Discovery:&discovery.Service{Store:st},Worker:&worker.Worker{Store:st,Crawler:crawl.New(time.Duration(cfg.HTTPTimeoutSeconds)*time.Second,cfg.MaxBodyBytes),MaxDepth:3,MaxPages:100,MaxCandidatesPerPage:50}}}
func(s *Server)ServeHTTP(w http.ResponseWriter,r *http.Request){if r.URL.Path=="/api/v1/health"{write(w,200,map[string]any{"status":"ok","service":"numpo-engine"});return};if s.Cfg.APIKey!=""&&r.Header.Get("Authorization")!="Bearer "+s.Cfg.APIKey{writeErr(w,401,"unauthorized","Authentication required.",false);return};switch{case r.Method==http.MethodPost&&r.URL.Path=="/api/v1/discovery/jobs":s.createJob(w,r);case r.Method==http.MethodGet&&strings.HasPrefix(r.URL.Path,"/api/v1/discovery/jobs/"):s.job(w,r);default:writeErr(w,404,"not_found","Route not found.",false)}}
func(s *Server)createJob(w http.ResponseWriter,r *http.Request){defer r.Body.Close();var p struct{ProjectID string;Mode string;Seeds []string;Sources map[string]bool};if e:=json.NewDecoder(http.MaxBytesReader(w,r.Body,s.Cfg.MaxBodyBytes)).Decode(&p);e!=nil{writeErr(w,400,"invalid_json","Invalid JSON.",false);return};if p.ProjectID==""{writeErr(w,400,"invalid_project_id","project_id is required.",false);return};if p.Mode!="manual"&&p.Mode!="automatic"&&p.Mode!="hybrid"{writeErr(w,400,"invalid_discovery_mode","Discovery mode is invalid.",false);return};if p.Mode=="manual"&&len(p.Seeds)==0{writeErr(w,400,"manual_seeds_required","Manual mode requires seeds.",false);return};id:=uuid.NewString();if e:=s.Store.CreateDiscoveryJob(r.Context(),id,p.ProjectID,p.Mode);e!=nil{writeErr(w,500,"internal_error","Could not create job.",true);return};if len(p.Seeds)>0{if e:=s.Discovery.Seed(r.Context(),id,p.Seeds);e!=nil{_ = s.Store.SetJobStatus(r.Context(),id,"failed");writeErr(w,400,"invalid_seed",e.Error(),false);return}};go func(){_ = s.Worker.Run(context.Background(),id)}();write(w,202,map[string]any{"job_id":id,"status":"queued","mode":p.Mode,"created_at":time.Now().UTC()})}
func(s *Server)job(w http.ResponseWriter,r *http.Request){parts:=strings.Split(strings.Trim(r.URL.Path,"/"),"/");if len(parts)<5{writeErr(w,404,"not_found","Job not found.",false);return};id:=parts[4];if len(parts)==6&&parts[5]=="candidates"{c,e:=s.Store.Candidates(r.Context(),id);if e!=nil{writeErr(w,500,"internal_error",e.Error(),true);return};write(w,200,map[string]any{"items":c});return};j,e:=s.Store.GetDiscoveryJob(r.Context(),id);if e!=nil{writeErr(w,404,"not_found","Job not found.",false);return};write(w,200,j)}
func write(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_ = json.NewEncoder(w).Encode(v)}
func writeErr(w http.ResponseWriter,status,code,message string,retry bool){write(w,status,map[string]any{"error":map[string]any{"code":code,"message":message,"retryable":retry}})}
