ALTER TABLE discovery_jobs ADD COLUMN IF NOT EXISTS configuration jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE discovery_jobs ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE discovery_jobs ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS source_id text NOT NULL DEFAULT '';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS queued_at timestamptz;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS processing_started_at timestamptz;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS completed_at timestamptz;
CREATE INDEX IF NOT EXISTS candidates_domain_queue_idx ON candidates(discovery_job_id,normalized_domain,status,priority DESC);
CREATE INDEX IF NOT EXISTS candidates_host_queue_idx ON candidates(discovery_job_id,normalized_host,status,priority DESC);
CREATE INDEX IF NOT EXISTS pages_depth_idx ON pages(domain_id,depth);
CREATE INDEX IF NOT EXISTS contacts_type_idx ON contacts(domain_id,type);
CREATE INDEX IF NOT EXISTS technologies_name_idx ON technologies(domain_id,name);
CREATE INDEX IF NOT EXISTS job_errors_job_idx ON job_errors(job_id,created_at DESC);
