package detect

import("net/url";"regexp";"strings";"github.com/samanramezani1377-hub/crawler-numpo/internal/model")

var phoneRe=regexp.MustCompile(`(?i)(?:\+?\d[\d\s().-]{7,}\d)`)
var emailRe=regexp.MustCompile(`(?i)[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,}`)
var addressRe=regexp.MustCompile(`(?is)(?:address|آدرس|نشانی)\s*[:：-]?\s*([^<\n]{5,180})`)
var socialRe=regexp.MustCompile(`(?i)https?://(?:www\.)?(instagram\.com|t\.me|telegram\.me|linkedin\.com|facebook\.com|youtube\.com|x\.com|twitter\.com)/[^\s\"'<>)]*`)

func Technologies(body,url string)[]model.Technology{l:=strings.ToLower(body);var out []model.Technology;if strings.Contains(l,"wp-content/")||strings.Contains(l,"wp-includes/"){out=append(out,model.Technology{Name:"WordPress",Confidence:.95,Evidence:[]string{"wp-content/wp-includes marker"},URL:url})};if strings.Contains(l,"woocommerce")||strings.Contains(l,"wc-ajax"){out=append(out,model.Technology{Name:"WooCommerce",Confidence:.9,Evidence:[]string{"woocommerce marker"},URL:url})};return out}
func Contacts(body,url string)[]model.Contact{seen:=map[string]bool{};var out []model.Contact;for _,v:=range emailRe.FindAllString(body,-1){v=strings.ToLower(v);if !seen["email:"+v]{seen["email:"+v]=true;out=append(out,model.Contact{Type:"email",Value:v,NormalizedValue:v,URL:url})}};for _,v:=range phoneRe.FindAllString(body,-1){n:=normalizePhone(v);if len(n)>=8&&!seen["phone:"+n]{seen["phone:"+n]=true;out=append(out,model.Contact{Type:"phone",Value:v,NormalizedValue:n,URL:url})}};return out}
func ClassifyPage(body,rawURL,title string)[]model.PageClassification{u,_:=url.Parse(rawURL);path:=strings.ToLower(u.Path);text:=strings.ToLower(body);var out []model.PageClassification;add:=func(c string,conf float64,e string){out=append(out,model.PageClassification{Class:c,Confidence:conf,Evidence:[]string{e},URL:rawURL})};if path==""||path=="/"{add("homepage",.95,"root path")};if strings.Contains(path,"contact")||strings.Contains(text,"contact us")||strings.Contains(text,"تماس با ما"){add("contact",.9,"contact marker")};if strings.Contains(path,"about")||strings.Contains(text,"about us")||strings.Contains(text,"درباره ما"){add("about",.85,"about marker")};if strings.Contains(path,"product")||strings.Contains(text,"add to cart")||strings.Contains(text,"افزودن به سبد"){add("product",.8,"product marker")};if strings.Contains(path,"category")||strings.Contains(path,"product-category"){add("category",.75,"category marker")};if strings.Contains(path,"blog")||strings.Contains(path,"news"){add("blog",.7,"blog/news path")};if strings.Contains(path,"checkout")||strings.Contains(text,"checkout"){add("checkout",.8,"checkout marker")};if strings.Contains(path,"cart")||strings.Contains(text,"shopping cart"){add("cart",.8,"cart marker")};if strings.Contains(path,"privacy")||strings.Contains(text,"privacy policy"){add("privacy",.9,"privacy marker")};if strings.Contains(path,"terms")||strings.Contains(text,"terms and conditions"){add("terms",.9,"terms marker")};_ = title;return out}
func Business(body,rawURL,title string)[]model.BusinessProfile{var out []model.BusinessProfile;name:=strings.TrimSpace(title);if name==""{name=extractMeta(body,"og:site_name")};address:="";if m:=addressRe.FindStringSubmatch(body);len(m)>1{address=strings.TrimSpace(m[1])};if name!=""||address!=""{out=append(out,model.BusinessProfile{Name:name,Address:address,Confidence:.65,URL:rawURL})};return out}
func Social(body,source string)[]model.SocialProfile{seen:=map[string]bool{};var out []model.SocialProfile;for _,raw:=range socialRe.FindAllString(body,-1){u,e:=url.Parse(raw);if e!=nil{continue};host:=strings.ToLower(u.Hostname());network:="";switch{case strings.Contains(host,"instagram.com"):network="instagram";case host=="t.me"||strings.Contains(host,"telegram.me"):network="telegram";case strings.Contains(host,"linkedin.com"):network="linkedin";case strings.Contains(host,"facebook.com"):network="facebook";case strings.Contains(host,"youtube.com"):network="youtube";case host=="x.com":network="x";case strings.Contains(host,"twitter.com"):network="x"};if network==""{continue};u.Fragment="";n:=u.String();key:=network+":"+n;if !seen[key]{seen[key]=true;out=append(out,model.SocialProfile{Network:network,URL:raw,NormalizedURL:n,Confidence:.95,SourceURL:source})}};return out}
func extractMeta(body,key string)string{needle:=strings.ToLower(key);l:=strings.ToLower(body);i:=strings.Index(l,needle);if i<0{return ""};tail:=body[i:];if j:=strings.Index(tail,">");j>=0{tail=tail[j+1:];if k:=strings.Index(tail,"<");k>=0{return strings.TrimSpace(tail[:k])}};return ""}
func normalizePhone(s string)string{var b strings.Builder;for _,r:=range s{if r>='0'&&r<='9'{b.WriteRune(r)}else if r=='+'&&b.Len()==0{b.WriteRune(r)}};return b.String()}
