package worker
import("context";"errors";"encoding/json";"net/url";"strings";"strconv";"time";"github.com/google/uuid";"github.com/samanramezani1377-hub/crawler-numpo/internal/model";"github.com/samanramezani1377-hub/crawler-numpo/internal/crawl";"github.com/samanramezani1377-hub/crawler-numpo/internal/detect";"github.com/samanramezani1377-hub/crawler-numpo/internal/probe";"github.com/samanramezani1377-hub/crawler-numpo/internal/policy";"github.com/samanramezani1377-hub/crawler-numpo/internal/routing";"github.com/samanramezani1377-hub/crawler-numpo/internal/store";"github.com/samanramezani1377-hub/crawler-numpo/internal/urlnorm")
type Worker struct{Store *store.Store;Crawler *crawl.Crawler;Prober *probe.Prober;MaxPages int;MaxCandidatesPerPage int;MaxDepth int;MaxURLs int;Lease time.Duration;DomainRateLimit time.Duration;ProbeTTL time.Duration;AllowSubdomains bool;AllowExternalLinks bool}
func(w *Worker)Run(ctx context.Context,job string)error{pages:=0;processed:=0;last:=map[string]time.Time{}
 for pages<w.MaxPages&&processed<w.MaxURLs{
  if ctx.Err()!=nil{return ctx.Err()}
  status,e:=w.Store.GetJobStatus(ctx,job);if e!=nil{return e};if status=="cancelled"||status=="completed"||status=="failed"{return nil}
  id,raw,domain,_,depth,e:=w.Store.ClaimCandidate(ctx,job,w.Lease);if e!=nil{if errors.Is(e,context.Canceled)||errors.Is(e,context.DeadlineExceeded){return e};return w.Store.FinishJobIfEmpty(ctx,job)};processed++
  allowed,e:=w.Store.ConsumeURLBudget(ctx,job);if e!=nil{return e};if !allowed{_ = w.Store.SetCandidateStatus(ctx,id,"failed_final","job URL budget exhausted");return w.Store.FinishJobIfEmpty(ctx,job)}
  if t:=time.Since(last[domain]);t<w.DomainRateLimit{d:=w.DomainRateLimit-t;timer:=time.NewTimer(d);select{case<-ctx.Done():timer.Stop();return ctx.Err();case<-timer.C:};};last[domain]=time.Now()
  jobInfo,e:=w.Store.GetDiscoveryJob(ctx,job);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue};projectID,_:=jobInfo["project_id"].(string);linkDiscovery:=true;activeProbe:=true;deepCrawl:=true;doPhone:=true;doEmail:=true;doBusiness:=true;doSocial:=true;doPageClass:=true;rules:=[]routing.Rule{};if cfg,ok:=jobInfo["config"].(map[string]any);ok{if caps,ok:=cfg["capabilities"].(map[string]any);ok{boolCap:=func(k string,d bool)bool{if v,exists:=caps[k];exists{if b,ok:=v.(bool);ok{return b}};return d};linkDiscovery=boolCap("link_discovery",linkDiscovery);activeProbe=boolCap("active_probe",activeProbe);deepCrawl=boolCap("deep_crawl",deepCrawl);doPhone=boolCap("phone",doPhone);doEmail=boolCap("email",doEmail);doBusiness=boolCap("business",doBusiness);doSocial=boolCap("social",doSocial);doPageClass=boolCap("page_classification",doPageClass)}if src,ok:=cfg["sources"].(map[string]any);ok{if v,exists:=src["link_discovery"];exists{if b,ok:=v.(bool);ok{linkDiscovery=b}}};if rr,ok:=cfg["routing_rules"];ok{if b,ok:=json.Marshal(rr);ok==nil{_ = json.Unmarshal(b,&rules)}}}
  domainID,e:=w.Store.EnsureDomain(ctx,projectID,domain);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue}
  host:=domain;if u,e:=url.Parse(raw);e==nil{host=strings.ToLower(u.Hostname())};hostID,e:=w.Store.EnsureHost(ctx,domainID,host);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue}
  if !activeProbe{_ = w.Store.SetCandidateStatus(ctx,id,"completed","active probe disabled");continue};fresh,active,e:=w.Store.ProbeFresh(ctx,hostID,w.ProbeTTL);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue};var pr model.ProbeResult;if fresh{status:="inactive";if active{status="active"};pr=model.ProbeResult{Host:host,Status:status}}else{pr,e=w.Prober.Probe(ctx,host)};_ = w.Store.UpsertProbe(ctx,hostID,pr.Status,"v1",pr.DNSStatus,pr.HTTPStatus,pr.HTTPSStatus,pr.RedirectTarget,pr.ResponseTimeMS,pr.ErrorCode,pr.ErrorMessage)
  if e!=nil||pr.Status!="active"{_ = w.Store.SetCandidateStatus(ctx,id,"completed",pr.ErrorMessage);_ = w.Store.UpsertSignal(ctx,domain,"probe","active","false",.9,nil,raw);continue};_ = w.Store.UpsertSignal(ctx,domain,"probe","active","true",1,nil,raw)
  if ok,e:=w.Store.ConsumePageBudget(ctx,job,domainID);e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue}else if !ok{_ = w.Store.SetCandidateStatus(ctx,id,"failed_final","job page budget exhausted");continue};p,e:=w.Crawler.Fetch(ctx,raw);if e!=nil{var he *crawl.HTTPError;if errors.As(e,&he){if he.Status==429||he.Status>=500{delay:=time.Second;if he.RetryAfter!=""{if n,pe:=strconv.Atoi(strings.TrimSpace(he.RetryAfter));pe==nil{delay=time.Duration(n)*time.Second}};_ = w.Store.RecordJobError(ctx,job,"http",strconv.Itoa(he.Status),e.Error(),true,1);_ = w.Store.ScheduleRetryAfter(ctx,id,e.Error(),delay);continue};_ = w.Store.RecordJobError(ctx,job,"http",strconv.Itoa(he.Status),e.Error(),false,1);_ = w.Store.SetCandidateStatus(ctx,id,"failed_final",e.Error());continue};_ = w.Store.RecordJobError(ctx,job,"network","crawl_error",e.Error(),true,1);_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue};pages++
  pageID,pageErr:=w.Store.UpsertPage(ctx,domainID,p.URL,p.Status,p.Title,p.ContentType,depth);if pageErr!=nil{_ = w.Store.ScheduleRetry(ctx,id,pageErr.Error(),0);continue};if doPageClass{for _,pc:=range detect.ClassifyPage(p.Body,p.URL,p.Title){_ = w.Store.UpsertPageClassification(ctx,domainID,pageID,pc.Class,pc.Confidence,pc.Evidence,pc.URL);_ = w.Store.UpsertSignal(ctx,domain,"page",pc.Class,"true",pc.Confidence,pc.Evidence,pc.URL)};};tech:=detect.Technologies(p.Body,p.URL);wp,wc:=false,false
  for _,t:=range tech{_ = w.Store.UpsertTechnology(ctx,domainID,t.Name,t.Version,t.Confidence,t.Evidence,t.URL);_ = w.Store.UpsertSignal(ctx,domain,"technology",t.Name,t.Version,t.Confidence,t.Evidence,t.URL);if t.Name=="WordPress"{wp=true};if t.Name=="WooCommerce"{wc=true}}
  for _,ct:=range detect.Contacts(p.Body,p.URL){if (ct.Type=="phone"&&!doPhone)||(ct.Type=="email"&&!doEmail){continue}_ = w.Store.UpsertContact(ctx,domainID,ct.Type,ct.Value,ct.NormalizedValue,ct.URL);_ = w.Store.UpsertSignal(ctx,domain,"contact",ct.Type,ct.NormalizedValue,1,nil,ct.URL)}
  };_ = w.Store.SetCandidateStatus(ctx,id,"completed","");decision:=routing.Route(true,wp,wc);if len(rules)>0{decision=routing.RouteWithRules(true,wp,wc,rules)};if !decision.DeepCrawl||!linkDiscovery||!deepCrawl{continue}
  for i,link:=range p.Links{if i>=w.MaxCandidatesPerPage||depth>=w.MaxDepth{break};u,e:=urlnorm.URL(link);if e!=nil||policy.ValidateURL(link)!=nil{continue};linkDomain,e:=urlnorm.Domain(link);if e!=nil{continue};same:=strings.EqualFold(linkDomain,domain);sub:=isSubdomain(linkDomain,domain);if !same&&!sub&&!w.AllowExternalLinks{continue};if sub&&!w.AllowSubdomains{continue};_ = w.Store.UpsertCandidateDepth(ctx,uuid.NewString(),job,link,u.String(),linkDomain,strings.ToLower(u.Hostname()),"deep_crawl",raw,50,.8,depth+1)}
 }
 return w.Store.FinishJobIfEmpty(ctx,job)
}
func isSubdomain(host,parent string)bool{host=strings.TrimSuffix(strings.ToLower(host),".");parent=strings.TrimSuffix(strings.ToLower(parent),".");return host!=parent&&strings.HasSuffix(host,"."+parent)}
