package worker
import("context";"errors";"encoding/json";"net/url";"strings";"strconv";"time";"github.com/google/uuid";"github.com/samanramezani1377-hub/crawler-numpo/internal/model";"github.com/samanramezani1377-hub/crawler-numpo/internal/crawl";"github.com/samanramezani1377-hub/crawler-numpo/internal/detect";"github.com/samanramezani1377-hub/crawler-numpo/internal/policy";"github.com/samanramezani1377-hub/crawler-numpo/internal/routing";"github.com/samanramezani1377-hub/crawler-numpo/internal/store";"github.com/samanramezani1377-hub/crawler-numpo/internal/urlnorm";"github.com/samanramezani1377-hub/crawler-numpo/internal/target";"github.com/samanramezani1377-hub/crawler-numpo/internal/browser";"github.com/samanramezani1377-hub/crawler-numpo/internal/retry")
type Crawler interface{Fetch(context.Context,string)(crawl.Page,error)}
type Prober interface{Probe(context.Context,string)(model.ProbeResult,error)}
type Worker struct{Store *store.Store;Crawler Crawler;Prober Prober;MaxPages int;MaxCandidatesPerPage int;MaxDepth int;MaxURLs int;Lease time.Duration;DomainRateLimit time.Duration;ProbeTTL time.Duration;AllowSubdomains bool;AllowExternalLinks bool;Browser browser.Renderer}
func(w *Worker)Run(ctx context.Context,job string)error{pages:=0;processed:=0
 maxPages,maxURLs,maxDepth,maxCandidates:=w.MaxPages,w.MaxURLs,w.MaxDepth,w.MaxCandidatesPerPage
 for pages<maxPages&&processed<maxURLs{
  if ctx.Err()!=nil{return ctx.Err()}
  status,e:=w.Store.GetJobStatus(ctx,job);if e!=nil{return e};if status=="cancelled"||status=="completed"||status=="failed"{return nil};if status=="paused"{timer:=time.NewTimer(2*time.Second);select{case <-ctx.Done():timer.Stop();return ctx.Err();case <-timer.C:};continue}
  id,raw,domain,_,depth,e:=w.Store.ClaimCandidate(ctx,job,w.Lease);if e!=nil{if errors.Is(e,context.Canceled)||errors.Is(e,context.DeadlineExceeded){return e};return w.Store.FinishJobIfEmpty(ctx,job)};processed++
  allowed,e:=w.Store.ConsumeURLBudget(ctx,job);if e!=nil{return e};if !allowed{_ = w.Store.SetCandidateStatus(ctx,id,"failed_final","job URL budget exhausted");return w.Store.FinishJobIfEmpty(ctx,job)}
  if e:=w.Store.AcquireDomainRateLimit(ctx,domain,w.DomainRateLimit);e!=nil{return e}
  jobInfo,e:=w.Store.GetDiscoveryJob(ctx,job);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue};projectID,_:=jobInfo["project_id"].(string);linkDiscovery:=true;activeProbe:=true;deepCrawl:=true;doPhone:=true;doEmail:=true;doBusiness:=true;doSocial:=true;doPageClass:=true;rules:=[]routing.Rule{};if cfg,ok:=jobInfo["config"].(map[string]any);ok{if v,ok:=cfg["max_pages"].(float64);ok&&v>0{maxPages=int(v)};if v,ok:=cfg["max_urls"].(float64);ok&&v>0{maxURLs=int(v)};if v,ok:=cfg["max_depth"].(float64);ok&&v>=0{maxDepth=int(v)};if v,ok:=cfg["max_candidates_per_page"].(float64);ok&&v>0{maxCandidates=int(v)};if caps,ok:=cfg["capabilities"].(map[string]any);ok{boolCap:=func(k string,d bool)bool{if v,exists:=caps[k];exists{if b,ok:=v.(bool);ok{return b}};return d};linkDiscovery=boolCap("link_discovery",linkDiscovery);activeProbe=boolCap("active_probe",activeProbe);deepCrawl=boolCap("deep_crawl",deepCrawl);doPhone=boolCap("phone",doPhone);doEmail=boolCap("email",doEmail);doBusiness=boolCap("business",doBusiness);doSocial=boolCap("social",doSocial);doPageClass=boolCap("page_classification",doPageClass)};if src,ok:=cfg["sources"].(map[string]any);ok{if v,exists:=src["link_discovery"];exists{if b,ok:=v.(bool);ok{linkDiscovery=b}}};if rr,ok:=cfg["routing_rules"];ok{if b,ok:=json.Marshal(rr);ok==nil{_ = json.Unmarshal(b,&rules)}}}
  domainID,e:=w.Store.EnsureDomain(ctx,projectID,domain);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue}
  host:=domain;if u,e:=url.Parse(raw);e==nil{host=strings.ToLower(u.Hostname())};hostID,e:=w.Store.EnsureHost(ctx,domainID,host);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue}
  if !activeProbe{_ = w.Store.SetCandidateStatus(ctx,id,"completed","active probe disabled");continue};fresh,active,e:=w.Store.ProbeFresh(ctx,hostID,w.ProbeTTL);if e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue};var pr model.ProbeResult;if fresh{status:="inactive";if active{status="active"};pr=model.ProbeResult{Host:host,Status:status}}else{pr,e=w.Prober.Probe(ctx,host)};_ = w.Store.UpsertProbe(ctx,hostID,pr.Status,"v1",pr.DNSStatus,pr.HTTPStatus,pr.HTTPSStatus,pr.RedirectTarget,pr.ResponseTimeMS,pr.ErrorCode,pr.ErrorMessage)
  if e!=nil||pr.Status!="active"{_ = w.Store.SetCandidateStatus(ctx,id,"completed",pr.ErrorMessage);_ = w.Store.UpsertSignal(ctx,domain,"probe","active","false",.9,nil,raw);continue};_ = w.Store.UpsertSignal(ctx,domain,"probe","active","true",1,nil,raw)
  if ok,e:=w.Store.ConsumePageBudget(ctx,job,domainID);e!=nil{_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue}else if !ok{_ = w.Store.SetCandidateStatus(ctx,id,"failed_final","job page budget exhausted");continue};p,e:=w.Crawler.Fetch(ctx,raw);if e==nil&&w.Browser!=nil&&shouldEscalateToBrowser(p){if br,be:=w.Browser.Render(ctx,raw);be==nil{if u,pe:=url.Parse(br.URL);pe==nil{p=crawl.Page{URL:br.URL,Status:br.Status,ContentType:br.ContentType,Body:br.HTML};p.Title,p.Links=crawl.ParseHTML(u,br.HTML,maxCandidates)}}};if e!=nil{if w.Browser!=nil{if br,be:=w.Browser.Render(ctx,raw);be==nil{if u,pe:=url.Parse(br.URL);pe==nil{p=crawl.Page{URL:br.URL,Status:br.Status,ContentType:br.ContentType,Body:br.HTML};p.Title,p.Links=crawl.ParseHTML(u,br.HTML,maxCandidates);e=nil}}}};if e!=nil{var he *crawl.HTTPError;if errors.As(e,&he){d:=retry.New(3,time.Second,30*time.Second,500*time.Millisecond).Decide(he,1);if d.Retry{_ = w.Store.RecordJobError(ctx,job,"http",strconv.Itoa(he.Status),e.Error(),true,1);_ = w.Store.ScheduleRetryAfter(ctx,id,e.Error(),d.Delay);continue};_ = w.Store.RecordJobError(ctx,job,"http",strconv.Itoa(he.Status),e.Error(),false,1);_ = w.Store.SetCandidateStatus(ctx,id,"failed_final",e.Error());continue};_ = w.Store.RecordJobError(ctx,job,"network","crawl_error",e.Error(),true,1);_ = w.Store.ScheduleRetry(ctx,id,e.Error(),0);continue};pages++
  pageID,pageErr:=w.Store.UpsertPage(ctx,domainID,p.URL,p.Status,p.Title,p.ContentType,depth);if pageErr!=nil{_ = w.Store.ScheduleRetry(ctx,id,pageErr.Error(),0);continue};if doPageClass{for _,pc:=range detect.ClassifyPage(p.Body,p.URL,p.Title){_ = w.Store.UpsertPageClassification(ctx,domainID,pageID,pc.Class,pc.Confidence,pc.Evidence,pc.URL);_ = w.Store.UpsertSignal(ctx,domain,"page",pc.Class,"true",pc.Confidence,pc.Evidence,pc.URL)}};tech:=detect.Technologies(p.Body,p.URL);wp,wc:=false,false;techNames:=make([]string,0,len(tech));for _,t:=range tech{techNames=append(techNames,t.Name);_ = w.Store.UpsertTechnology(ctx,domainID,t.Name,t.Version,t.Confidence,t.Evidence,t.URL);_ = w.Store.UpsertSignal(ctx,domain,"technology",t.Name,t.Version,t.Confidence,t.Evidence,t.URL);if t.Name=="WordPress"&&capEnabled(jobInfo,"wordpress",true){wp=true};if t.Name=="WooCommerce"&&capEnabled(jobInfo,"woocommerce",true){wc=true}};hasPublicPhone:=false;for _,ct:=range detect.Contacts(p.Body,p.URL){if ct.Type=="phone"{hasPublicPhone=true};if (ct.Type=="phone"&&!doPhone)||(ct.Type=="email"&&!doEmail){continue};_ = w.Store.UpsertContact(ctx,domainID,ct.Type,ct.Value,ct.NormalizedValue,ct.URL);_ = w.Store.UpsertSignal(ctx,domain,"contact",ct.Type,ct.NormalizedValue,1,nil,ct.URL)};targetCfg:=target.Config{};if cfg,ok:=jobInfo["config"].(map[string]any);ok{if rawTarget,ok:=cfg["target"].(map[string]any);ok{targetCfg=target.FromMap(rawTarget)}};if !targetCfg.Match(p.URL,p.Body,techNames,hasPublicPhone){_ = w.Store.SetCandidateStatus(ctx,id,"completed","target_mismatch");continue};if doBusiness{for _,bp:=range detect.Business(p.Body,p.URL,p.Title){_ = w.Store.UpsertBusiness(ctx,domainID,bp.Name,bp.Description,bp.Address,bp.URL,bp.Confidence);_ = w.Store.UpsertSignal(ctx,domain,"business","profile",bp.Name,bp.Confidence,nil,bp.URL)}};if doSocial{for _,sp:=range detect.Social(p.Body,p.URL){_ = w.Store.UpsertSocial(ctx,domainID,sp.Network,sp.URL,sp.NormalizedURL,sp.SourceURL,sp.Confidence);_ = w.Store.UpsertSignal(ctx,domain,"social",sp.Network,sp.NormalizedURL,sp.Confidence,nil,sp.SourceURL)}};_ = w.Store.SetCandidateStatus(ctx,id,"completed","");decision:=routing.Route(true,wp,wc);if len(rules)>0{decision=routing.RouteWithRules(true,wp,wc,rules)};if !decision.DeepCrawl||!linkDiscovery||!deepCrawl{continue}
  for i,link:=range p.Links{if i>=maxCandidates||depth>=maxDepth{break};u,e:=urlnorm.URL(link);if e!=nil||policy.ValidateURL(link)!=nil{continue};linkDomain,e:=urlnorm.Domain(link);if e!=nil{continue};same:=strings.EqualFold(linkDomain,domain);sub:=isSubdomain(linkDomain,domain);if !same&&!sub&&!w.AllowExternalLinks{continue};if sub&&!w.AllowSubdomains{continue};_ = w.Store.UpsertCandidateDepth(ctx,uuid.NewString(),job,link,u.String(),linkDomain,strings.ToLower(u.Hostname()),"deep_crawl",raw,50,.8,depth+1)}
 }
 return w.Store.FinishJobIfEmpty(ctx,job)
}
func isSubdomain(host,parent string)bool{host=strings.TrimSuffix(strings.ToLower(host),".");parent=strings.TrimSuffix(strings.ToLower(parent),".");return host!=parent&&strings.HasSuffix(host,"."+parent)}

func capEnabled(jobInfo map[string]any,key string,def bool) bool { cfg,ok:=jobInfo["config"].(map[string]any); if !ok{return def}; caps,ok:=cfg["capabilities"].(map[string]any); if !ok{return def}; v,ok:=caps[key].(bool); if !ok{return def}; return v }

func shouldEscalateToBrowser(p crawl.Page) bool {
 if p.Status < 200 || p.Status >= 300 || !strings.Contains(strings.ToLower(p.ContentType),"text/html") { return false }
 body := strings.ToLower(p.Body)
 if len(body) == 0 || len(body) > 512*1024 { return false }
 if !strings.Contains(body,"<script") { return false }
 markers := []string{"id=\"root\"","id=\"app\"","id=\"__next\"","id=\"__nuxt\"","ng-version","data-reactroot"}
 for _, marker := range markers { if strings.Contains(body,marker) { return true } }
 return strings.Count(body,"<script") >= 3 && !strings.Contains(body,"<main")
}
