package store

import("context";"time";"github.com/jackc/pgx/v5/pgxpool")
type Store struct{DB *pgxpool.Pool}
func New(ctx context.Context,dsn string)(*Store,error){db,e:=pgxpool.New(ctx,dsn);if e!=nil{return nil,e};if e=db.Ping(ctx);e!=nil{db.Close();return nil,e};return &Store{db},nil}
func(s *Store)Close(){s.DB.Close()}
func(s *Store)CreateDiscoveryJob(ctx context.Context,id,project,mode string)error{_,e:=s.DB.Exec(ctx,`INSERT INTO discovery_jobs(id,project_id,mode,status) VALUES($1,$2,$3,'queued')`,id,project,mode);return e}
func(s *Store)GetDiscoveryJob(ctx context.Context,id string)(map[string]any,error){r:=s.DB.QueryRow(ctx,`SELECT id,project_id,mode,status,created_at,updated_at FROM discovery_jobs WHERE id=$1`,id);var a,b,c,d string;var x,y time.Time;if e:=r.Scan(&a,&b,&c,&d,&x,&y);e!=nil{return nil,e};return map[string]any{"job_id":a,"project_id":b,"mode":c,"status":d,"created_at":x,"updated_at":y},nil}
func(s *Store)SetJobStatus(ctx context.Context,id,status string)error{_,e:=s.DB.Exec(ctx,`UPDATE discovery_jobs SET status=$2,updated_at=now() WHERE id=$1`,id,status);return e}
func(s *Store)UpsertCandidate(ctx context.Context,id,job,u,nu,domain,host,source,parent string,priority int,confidence float64)error{_,e:=s.DB.Exec(ctx,`INSERT INTO candidates(id,discovery_job_id,url,normalized_url,normalized_domain,normalized_host,source_type,parent_url,priority,confidence,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'new') ON CONFLICT(discovery_job_id,normalized_url) DO NOTHING`,id,job,u,nu,domain,host,source,parent,priority,confidence);return e}
func(s *Store)Candidates(ctx context.Context,job string)([]map[string]any,error){rows,e:=s.DB.Query(ctx,`SELECT id,url,normalized_url,normalized_domain,normalized_host,source_type,parent_url,priority,confidence,status,attempt_count,last_error,discovered_at FROM candidates WHERE discovery_job_id=$1 ORDER BY priority DESC,discovered_at`,job);if e!=nil{return nil,e};defer rows.Close();var out []map[string]any;for rows.Next(){var id,u,nu,d,h,src,parent,status,last string;var p,a int;var c float64;var at time.Time;if e=rows.Scan(&id,&u,&nu,&d,&h,&src,&parent,&p,&c,&status,&a,&last,&at);e!=nil{return nil,e};out=append(out,map[string]any{"id":id,"url":u,"normalized_url":nu,"normalized_domain":d,"normalized_host":h,"source_type":src,"parent_url":parent,"priority":p,"confidence":c,"status":status,"attempt_count":a,"last_error":last,"discovered_at":at})};return out,rows.Err()}
